### ISSUE TITLE
delete php sync file when deleted in ACF editor

### ISSUE THREAD

**Issue by yangkennyk** [acf-extended/ACF-Extended#10]
**Is your feature request related to a problem? Please describe.**
sometimes I delete a field in ACF and forget that the php sync file is still there until I come across a page a wonder why that field is there still. so I have to manually find it and delete it.

**Describe the solution you'd like**
The php sync file is deleted when the field is deleted in ACF. Like how the json file is deleted.

**Comment by acf-extended** [comment]
Hello!

Yes I stumbled upon this behavior earlier this week. You're right, PHP sync files should be removed when you trash Field Groups (just like it does with Json Sync).

I will add this in the next ACF Extended update!

Regards.

**Comment by acf-extended** [comment]
Hello,

Just to let you know that the latest 0.8.4 update include this fix 🙂

Regards.

**Comment by carasmo** [comment]
I don't know if this is related, but I'm using json sync and when ACE is installed the files won't initially save to the sync folder upon update. When ACE is deactivated, they do. I am at a loss. Is there some filter or setting I'm missing?

**Comment by acf-extended** [comment]
Hello,

When you activate ACF Extended, you get the control of which field group should be saved to Json or/and PHP.

By default, field groups are not saved to Json. In order to allow Json save, you have to manually check the "Json" checkbox in the field group administration, on the right side, then save your field group.

Screenshot:

![2020-01-25_14h57_57](https://user-images.githubusercontent.com/53943543/73122295-1b505c00-3f7b-11ea-94d9-7f1a9d31438e.png)

This way you get full control of what field groups are doing :)
