### ISSUE TITLE
Flexible content field. Global post variable in field "Relationship".

### ISSUE THREAD

**Issue by Danil-Klimov** [acf-extended/ACF-Extended#100]
**Describe the bug**
I am using a flexible content field. In this field I use relationship field. When i display this field in the frontend, the global variable ($post) is not set. Instead of the post title, the title of the current page is displayed for the entire set of posts.

**To Reproduce**
- created the flexible content field
- added a new section for posts loop inside the flexible content field
- wrote the template file path to be able to render it

**Expected behavior**
Posts displaying properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/22667759/170260336-2e0bf6f2-bb69-4c74-b8f7-52cfe3d41399.png)
![image](https://user-images.githubusercontent.com/22667759/170260743-5d8cd535-f076-4499-ba24-52feee4537de.png)
![image](https://user-images.githubusercontent.com/22667759/170260960-de50a30a-795a-4e05-a967-243770813ea7.png)
```php
<?php $products = get_sub_field('products'); ?>
<?php if($products) : ?>
  <?php foreach ($products as $post) : setup_postdata($post); ?>
    <p><?php the_title(); ?></p>
  <?php endforeach; wp_reset_postdata(); ?>
<?php endif; ?>
```

**WordPress & ACF**
WordPress version: 6.0
ACF Pro version: 5.12.2
ACF add-ons: ACF Extended 0.8.8.6

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback, and sorry for the late answer.

When using the Flexible Content Dynamic Render/Preview, you're rendering your layout template from a function: `the_flexible()`.

In order to use the WP `$post` variable (by `setup_postdata()` & `wp_reset_postdata()`), you have to add a `global $post` in your PHP code, in order to scope that global in the function. Usage example:

```php
<?php 
global $post;
$products = get_sub_field('products'); ?>
<?php if($products) : ?>
    <?php foreach ($products as $post) : setup_postdata($post); ?>
        <p><?php the_title(); ?></p>
    <?php endforeach; wp_reset_postdata(); ?>
<?php endif; ?>
```

To avoid using that `global $post`, you could generate a `new WP_Query()` using the sub fields values ids, since `$query->the_post()` already does the `global $post`. Usage example:

```php
<?php 
// use format_value = false to only get post ids
$products = get_sub_field('products', false); ?>

<?php
$query = new WP_Query(array(
    'post_type' => 'any',
    'post__in'  => $products,
    'orderby'   => 'post__in',
    'nopaging'  => true,
));
?>

<?php if($query->have_posts()): ?>
    <?php while($query->have_posts()): $query->the_post(); ?>
        <p><?php the_title(); ?></p>
    <?php endwhile; wp_reset_postdata(); ?>
<?php endif; ?>
```

Hope it helps!

Have a nice day!

Regards.
