### ISSUE TITLE
Dynamic preview flexible content nesting in each other and the modal cannot be clicked open

### ISSUE THREAD

**Issue by nielsreijnders** [acf-extended/ACF-Extended#115]
**Describe the bug**
Dynamic preview flexible content nesting in each other and the modal cannot be clicked open

**To Reproduce**
Add a few banner components with a dynamic preview in it. Click on publish. Refresh the page in the backend.

**Expected behavior**
I want to edit the component. Also when moving one of the components all the grouped components are going with them.

**Screenshots**
![alt text](https://i.imgur.com/u1KQB7D.png)
![alt text](https://i.imgur.com/tTxDBix.png)

**WordPress & ACF**
WordPress version: 6.2.2
ACF Pro version: 6.1.6 
ACF extended:  0.8.9.3

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

Not sure to understand if the issue is that you have nested Flexible Content when it shouldn't (I see banner > in a banner > in a banner).

Nested Flexible Content with Dynamic Preview is totally doable, and works fine with "Modal Edit" setting too. [Here is a video demo](https://www.acf-extended.com/share/cG9Cg).

Can you provide more details/screenshots/video showing the issue?

Regards.
