### ISSUE TITLE
JSON sync & category issue

### ISSUE THREAD

**Issue by MrCarlLister** [acf-extended/ACF-Extended#27]
**Describe the bug**
If a flexible content block does not have acfe_flexible_category set, this particular flexible content block and all those after it in the list, show up in all category selections.

For example if we have categories
Text
Image
Products

And flexible content blocks
FCB 1 (Text)
FCB 2 (Image)
FCB 3 (BLANK)
FCB 4 (Text)
FCB 5 (Products)

3, 4 & 5 would appear under all 3 categories.

**To Reproduce**
Settings include;
A flexible content field
Advanced flexible content
Stylised Button
Layouts Modal: Edition
Layouts Modal: Selection (categories ticked)

The field in question is set to json sync.

**Expected behavior**
Either Categories to be mandatory OR a layout block without a category set to only show in the 'all' category. All other layouts to appear where set.

**WordPress & ACF**
WordPress version: 5.3.2
ACF Pro version: 5.8.8
ACF add-ons: Advanced Custom Fields: Extended (0.8.4.6)

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! I already had a similar feedback about that specific behavior. The problem came from the the category input. The user has set categories using pipes, but added some spaces.

Example: `category 1 | category 2` instead of `category1|category2`. Can you please check that you don't add spaces between `|`? If so, remove them.

The next patch will add auto trim for that input to fix it.

Have a nice day!

Regards.

**Comment by MrCarlLister** [comment]
Thanks for your reply. There were no spaces between `|`. I had left a flexible content category empty entirely, which was causing the issue in the original post. 

Hope that helps!

**Comment by acf-extended** [comment]
Hello,

Roger that, I'm gonna run some tests with that specs then!

Will tell you as soon as I got some news.

Regards.

**Comment by acf-extended** [comment]
Hello,

I'm closing this ticket since it has been resolved in a past update.

Regards.
