### ISSUE TITLE
advanced link "type" and "post" fields missing

### ISSUE THREAD

**Issue by yangkennyk** [acf-extended/ACF-Extended#31]
I was relying on the "type" and "post" values in the advanced link array to do some logic but it seems like the latest update removed those fields.

how can I get those back?

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! There have been some changes in the Advanced Link in the latest update. It now works properly, and it's also more clean :)

In order to retrieve "raw" data from the field, you should get unformatted value, like this:

`get_field('my_advanced_link', 12, false);` (`false` as third argument)

The return value will be:

```
Array
(
    [type] => post
    [post] => 536
    [title] => My link
    [target] => 1
)
```

Note: As user can now select a post type archive link, the `post` key will return the `post type name` if the user selected a post type archive. Example:

```
Array
(
    [type] => post
    [post] => my-post-type
    [title] => My post type archive
    [target] => 1
)
```

So you should check is `is_numeric($post)` to know if you have to deal with `post id` or `post type archive`. And if the user select a term (it's also a new feature), the returning value will be:

```
Array
(
    [type] => term
    [post] => 1
    [title] => My term
    [target] => 1
)
```

Hope it helps :)

Have a nice day!

Regards.
