### ISSUE TITLE
Feature request: Unload css and js if feature is not enabled or in use

### ISSUE THREAD

**Issue by alriksson** [acf-extended/ACF-Extended#34]
**Is your feature request related to a problem? Please describe.**
See some js and CSS that I think I wouldn't need to load, they are small but still if not in use I would prefer to not load them.

**Full list of styles:**
acf-extended.css?ver=0.8.5
acf-extended-admin.css?ver=0.8.5 _Needed to load on edit-post?_
acf-extended-modal.css?ver=0.8.5
acf-extended-fc.css?ver=0.8.5
acf-extended-taxonomies.css?ver=0.8.5
acf-extended-repeater.css?ver=0.8.5
acf-extended-fc-control.css?ver=0.8.5
acf-extended-fc-modal-edit.css?ver=0.8.5

**Full list of Scripts:**
acf-extended-fc-control.js?ver=0.8.5
acf-extended-fc.js?ver=0.8.5
acf-extended-fc-modal-select.js?ver=0.8.5
acf-extended.js?ver=0.8.5
acf-extended-repeater.js?ver=0.8.5
acf-extended-fc-modal-edit.js?ver=0.8.5

**Describe the solution you'd like**
Add filters or options in settings to not load assets if not used.

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback. This feature request is similar to the feedback you wrote here: https://wordpress.org/support/topic/optimize-wp-admin/

I already added it to the to-do list: https://trello.com/c/WuBRkr7F/15-minify-wp-admin-css-js-files

Those files are all mandatory in order to make all fields & features work correctly. Similar to ACF files `acf-input.js` & `acf-input.css` which regroup all JS & CSS rules for all fields. I plan to regroup and minify them the same ACF does.

I'm closing the ticket as duplicate.

**Comment by alriksson** [comment]
I agree, and thanks! You too!
