### ISSUE TITLE
Fields on archive pages + WPML

### ISSUE THREAD

**Issue by rcobiella** [acf-extended/ACF-Extended#46]
**Describe the bug**
Fields on archive pages do not seem to be translatable.

**To Reproduce**
Add fields to a custom post type archive page. Set the fields as translatable (with ACF Multilingual plugin by WPML). Once you save the fields content, switch language, and it's the same in every language.

**Expected behavior**
To be able to save different values for each different language.

**WordPress & ACF**
WordPress version: 5.4.2
ACF Pro version: 5.8.12
WPML version: 4.3.15
ACF add-ons: ACF Extended (0.8.6.3), ACF Multilingual (1.7.1)

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback. The "Post Type Archive Page" is a virtual Options Page that is automatically generated. It is registered and behave like any other Options Page. In order to translate those data, you'll need to follow WPML way to translate ACF Options Page. Here are some topics about it:

- https://wpml.org/forums/topic/acf-not-translating-independently-on-options-page/
- https://wpml.org/forums/topic/acf-options-pages-are-not-duped-translated/
- https://wpml.org/forums/topic/acf-options-page-in-other-languages-not-visible/

Note: I would recommend to avoid WPML and use Polylang instead. It has an ACF Options page plugin which works very nicely!

Regards.

**Comment by rcobiella** [comment]
Thanks! This helped a lot.

And yeah, WPML is the worst and I try avoiding it as much as I can. Countless bugs and compatibility issues, release after release, it's endless. I haven't used Polylang in years, as most end clients tend to prefer WPML, but it seems I missed the last couple of years of updates and looks much better now, so I'll definitely have a look at it. Thank you for the tip.
