### ISSUE TITLE
Field Type / Field group show "Undefined" for fields in use when fields are part of Clone

### ISSUE THREAD

**Issue by codemonkeynorth** [acf-extended/ACF-Extended#49]
**Describe the bug**
In the **ACF Custom Fields** list several entries show with Field Type / Field Group `Undefined` even though they are actual entries with content for instance in the screenshot `flexible_content_blocks_0_title` is just a plain text field. However the likely reason is that it's actually implemented within a Clone of another set of Custom Fields, within a Flexible Layout

eg I have
**Custom Field Group:** Block Title With Content
**Custom Field Group:** Flexible Content Blocks

in one of the **Flexible Content Blocks** Layouts we use an ACF Clone of the "Block Title With Content" field group for its fields (this way we can manage the fields for each flexible layout separately)

I was going to delete the Undefined entries, thinking they were orphaned data from removing flexible content but this is not the case - they are definitely in use. So I think it's just an issue with picking up the original field type from the Clone

**To Reproduce**
not sure

**Expected behavior**
Field Type / Field Group should show the correct data

**Screenshots**
**ACFE**
![field_types](https://user-images.githubusercontent.com/20189985/86470579-9ccec600-bd33-11ea-8724-792672c4e98f.png)

**Field Group: Flexible Content Blocks**
![image](https://user-images.githubusercontent.com/20189985/86471542-76118f00-bd35-11ea-8f18-eb3b59f90552.png)
![image](https://user-images.githubusercontent.com/20189985/86471591-917c9a00-bd35-11ea-99fb-668214690b75.png)

**Field Group: Block Title With Content**
![image](https://user-images.githubusercontent.com/20189985/86471644-ae18d200-bd35-11ea-9683-27f5fff476e1.png)

**WordPress & ACF**
WordPress version: 5.4.2
ACF Pro version: 5.8.12
ACF add-ons: ACF Content Analysis for Yoast SEO, ACF Better Search, Advanced Custom Fields: Extended, Advanced Custom Fields: Image Aspect Ratio Crop

thanks

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! You're right, clone fields inside sub fields (like in the Flexible Content) aren't supported by the Meta Overiview of the Dev Mode, due to the specific `field_key` concatenation. Clone field is a really complex field on it's own, everytime in get inside its code, I feel like I'm entering the void :D

![ACF Clone Field](https://user-images.githubusercontent.com/53943543/86485219-78d1ab80-bd58-11ea-8bba-ab377e2eab1c.gif)

I've added an extra check for that specific case. The fix will be added in the next patch. See screenshot:
![2020-07-03_18h09_16](https://user-images.githubusercontent.com/53943543/86485347-c77f4580-bd58-11ea-9277-d32c5b23ad08.png)

Regards.

**Comment by codemonkeynorth** [comment]
Perfect thanks!

**Comment by acf-extended** [comment]
Hello,

The latest ACF Extended 0.8.6.5 update fixed this issue!

Have a nice day.

Regards.
