### ISSUE TITLE
Post type Archive customizable Capability

### ISSUE THREAD

**Issue by stilografico** [acf-extended/ACF-Extended#53]
Hello,
I'm trying to let editors (or other custom roles) access to Post type Archive option pages.
I found out the line of code where the needed capability is set
**acf-extended/includes/locations/post-type-archive.php** line 45
 acf_add_options_page(.......
**'capability'	            => acf_get_setting('capability'),**
.....));

What I'm trying to do is to alter the capability parameter in my theme's functions using ACF available filters but it seems like, once the option page is already set, its settings are not editable anymore.

Do you already have any hook solution to suggest, like filters or similar?
Do you plan to make this configurable maybe with an optional paramer to set up on the CPT registering action?

In this very moment I went for a workaround allowing editor to access all ACF settings
`add_action('acf/init', 'alter_acf_capabilities');
function alter_acf_capabilities() {
    acf_update_setting('capability', 'edit_pages');

}`
then I will hide ACF Setting from the menu for non admin, but I don't like this solution at all.

Last but not least: thank you for you great efforts, this plugin is literally awesome and fills properly what ACF itself was missing.

Andrea

**Comment by PaulMorel** [comment]
I second this feature request. I've just encountered this with a website I'm working on. The client (Editor role) needs to be able edit to the fields I've setup in a post type archive option page, however I don't want to give them access to the ACF Settings pages.

I think by default it should mirror the post type's capabilities in someway. As someone who can edit those posts, should most likely be able to edit the archive's contents.

I think I could manage to submit a PR if this change is desirable.

@stilografico Thanks for the workaround. As I needed to find a solution ASAP.

**Comment by acf-extended** [comment]
Hello,

Sorry for the (very) late answer. You're right, developers should be able to change the Post Type Archive page capability individually, since it's a page which is quite outside of the ACF Field Group admin UI.

For reference, you can use the `acf/get_options_page` filter to change any ACF options page settings (including capability). While this hook is not officially documented, I talk about it in the [Options Page module documentation here](https://www.acf-extended.com/features/modules/dynamic-options-pages#settings-in-php).

The thing is that using this hook won't have effect on the "Edit Post type Archive" Admin Bar menu item which is added on front-end when visiting the post type archive page (which should definitely check the capability). So I decided to add a specific filter to change the capability in the upcoming patch. The hook will be added to the documentation:

```php
// You may also use: acfe/post_type_archive_capability/name=my-post-type
add_filter('acfe/post_type_archive_capability', 'my_acfe_post_type_archive_capability', 10, 2);
function my_acfe_post_type_archive_capability($capability, $post_type){
    
    $capability = 'edit_posts';
    return $capability;
    
}
```

I'll let you know once the patch is up. I guess it's better late than never :\

Sorry for the inconvenience.

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up to let you know that the latest ACF Extended 0.8.8.1 patch added this new feature!

Have a nice day!

Regards.
