### ISSUE TITLE
"acfe/modules/author" requires registering CPT with priority 1 or author metabox is hidden

### ISSUE THREAD

**Issue by yangkennyk** [acf-extended/ACF-Extended#6]
just a note for people that may have run into this because I spent a day trying to figure out why my author meta box was disappearing when ACFE was enabled. 

if you're registering a post type on "init" you have to set priority 1 or else the "acfe/modules/author" module doesn't catch the cpt "supports" variables.

get_post_types_by_support() that's being used in ACFE will only return the default post types that support "author"

so use

add_action( 'init', 'cptui_register_my_cpts' , 1);

the author metabox is also hidden if you use cptui to manage your registrations. you'll have to export the php and set the priority to 1

**Comment by acf-extended** [comment]
Hello,

Yes you're right. To be more specific, you have to hook on `init` on priority below `5`. This is because ACF Extended use the `acf/init` hook which hook on `init` priority `5`.

I'll fix this issue in the next patch, so you will be able to register your post type on `init` in any priority below `999`.

Thanks for the report, and sorry for the inconvenience.

I'll let you know as soon as the patch is up!

Regards.

**Comment by acf-extended** [comment]
Hello yangkennyk ,

Just to let you know that the latest ACF Extended 0.8.3 Update fixed this issue. you can now correctly register you post type with any priority (below `999`), and the author module will now correctly work.

Have a nice day!

Regards.
