### ISSUE TITLE
Draft post created when acfe/form/submit/post_args/ return false;

### ISSUE THREAD

**Issue by balintgaspar** [acf-extended/ACF-Extended#64]
**Describe the bug**
if I'm using add_filter('acfe/form/submit/post_args/form=booking', 'booking_post_args', 10, 4); and the booking_post_args function returns false, i got an empty draft post. I'm using the filter when creating a custom_post_type 'bookingentries' through acfe form.

**To Reproduce**
1.create acfe form
2. add save action
3. create the filter function to return false;
4. You got a draft post with the title 'Post'

**Expected behavior**
No draft post created.

**Screenshots**

**WordPress & ACF**
WordPress version: 5.5.3
ACF Pro version: 5.9.3
ACF add-ons: -

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! Yes, you're right, if you stop the post creation using `return false` in the `acfe/form/submit/post_args` hook, then there is a ghost draft "Post" that is remaining.

This is due to how ACF Extended Forms handle Post Creation with the Post Action. In order to be able to use the Post ID as Post Title or Post Slug, ACF Extended Form first insert a ghost draft post, then update it after the `acfe/form/submit/post_args` hook.

I'll add a fix to remove that ghost post if the developer decide to stop the psot creation within the `acfe/form/submit/post_args` hook.

Meanwhile, and generally speaking, I would advise you to use the [`acfe/form/prepare/post` hook](https://www.acf-extended.com/features/modules/dynamic-forms/post-action#prepare) to stop the Post Action. This "prepare" hook is triggered at the very beginning of the action (before anything is actually done), and let you stop the action. You still have access to all visitors input values there too, and can simply stop the action using `return false`.

I've added the bugfix in the Trello Board: https://trello.com/c/2kg0scHi/430-dynamic-forms-remove-ghost-post-draft-if-the-post-action-is-stopped-during-the-postargs-hook

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up to let you know that the latest ACF Extended 0.8.7.5 Update fix this issue!

Sorry for the inconvenience.

Have a nice day!

Regards.
