### ISSUE TITLE
If this plugin enabled "Add new user" -button will missing

### ISSUE THREAD

**Issue by Jntz** [acf-extended/ACF-Extended#68]
**Describe the bug**
When ACF_Extended plugin is activated, admin cannot create new user in user-new.php page.

**To Reproduce**
1. Activate ACFE
2. Trying to make new user. Add button missing. (screenshot: https://prnt.sc/wmtspv)
3. Deactivate ACFE
3. Trying to make new user. Everything working properly (screenshot: https://prnt.sc/wmttjq)

**Expected behavior**

**Screenshots**
ACFE activated: https://prnt.sc/wmtspv
ACFE deactivated: https://prnt.sc/wmttjq

**WordPress & ACF**
WordPress version: 5.6
ACF Pro version: 5.9.3
ACF add-ons:none

I have some extra fields to user and website use multisite feature.

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! This issue has been reported for WPMU users and will be fixed in the upcoming patch. In the meantime, you can disable the Enhanced UI module using the following code to fix the issue:

```php
add_action('acf/init', 'my_acfe_modules');
function my_acfe_modules(){

    acf_update_setting('acfe/modules/ui', false);
    
}
```

Regards.

**Comment by danimalweb** [comment]
I am also experiencing this issue. Looking forward to the patch. Thanks!

**Comment by Jntz** [comment]
Thank you!

**Comment by acf-extended** [comment]
Hello Everyone,

Just a small update on the upcoming patch. The next update takes a little bit longer as expected, because it's quite ambitious and has many new features. I'm working full time on it in order to release it as soon as possible. Just a little more patience, we're not too far away from release!

In the meantime, here is an updated code to disable the Enhanced UI Module only on Multisite New User screen, so you can still enjoy it on other screens (Terms, User Edit, WP Settings...):

```php
add_action('acf/init', 'my_acfe_disable_enhanced_ui_multisite');
function my_acfe_disable_enhanced_ui_multisite(){

    global $pagenow;
    
    // Disable Enhanced UI on Multisite New User Screen only
    if($pagenow === 'user-new.php' && is_multisite()){

        acf_update_setting('acfe/modules/ui', false);

    }

}
```

Sorry for the inconvenience.

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up to let you that the latest 0.8.8 Update fixed this issue.

Have a nice day!

Regards.
