### ISSUE TITLE
Does Elementor support fields from "group" acf-extended?

### ISSUE THREAD

**Issue by dwinskiy** [acf-extended/ACF-Extended#69]
I can't pick fields, which are made in group.
Does Elementor support it at all?
screen in attached
![redx](https://user-images.githubusercontent.com/28457994/105716587-1af0f500-5f30-11eb-8f62-ba1b533c345c.jpg)

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! Unfortunately I'm not an Elementor user, but I wouldn't be surprised that Elementor doesn't support fields with sub fields like Group/Flexible Content/Repeater, due to the complex nature of those fields.

The group field is a native ACF Pro field tho, I would suggest to open a support ticket on the Elementor or ACF GitHub for questions relative to its support.

Hope it helps!

Regards.
