### ISSUE TITLE
Feature request: Delete orphan meta from options page

### ISSUE THREAD

**Issue by wpsumo** [acf-extended/ACF-Extended#72]
**Is your feature request related to a problem? Please describe.**
Delete orphan and empty entries from all acf meta fields no matter where the field was located, post, post type, archive, options page.

**Describe the solution you'd like**
Bulk option page to handle orphans and single meta would be very nice.

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

The "Delete Orphan Meta" setting was removed from the Options Pages UI due to the fact that they are quite special. in fact, multiple Options Pages can share the same "Post ID" (in contrary to psots/terms/users). Due to the logic of the current "Delete Orphan Meta" logic and in some specific, that could lead to erase other Options Page sharing the same Post ID, which is definitely not intended.

This logic will be enhanced in the future. I don't have any ETA yet tho but it's planned.

I'm closing the ticket here.

Regards.

**Comment by wpsumo** [comment]
>The "Delete Orphan Meta" setting was removed from the Options Pages UI due to the fact that they are quite special. in fact, multiple Options Pages can share the same "Post ID" (which is not the case for posts/terms/users).

>Due to the logic of the current "Delete Orphan Meta", that could lead to erase other Options Page sharing the same Post ID in some specific situations, which is definitely not intended.

Yeah I remember that. What happens if we still use single meta for options page though?


>This logic will be enhanced in the future. I don't have any ETA yet tho, but it's planned.

Noted thanks! :)

**Comment by acf-extended** [comment]
Hello,

Single Meta Save works normally on Options Pages. It saves custom fields in one single meta prefixed with post id.

Regards.
