### ISSUE TITLE
Many notices after recent update

### ISSUE THREAD

**Issue by worldoptimizer** [acf-extended/ACF-Extended#75]
**Describe the bug**
We are getting many notices breaking execution after recent updates (debug mode enabled)

![CleanShot 2021-03-22 at 15 48 58@2x](https://user-images.githubusercontent.com/1752114/112008868-2cb4da00-8b26-11eb-9c95-2c03bcf40043.png)

**To Reproduce**
Enable wp debugging

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! You're right, this notice can be triggered when using Field Group Permission setting with the latest patch. I'm preparing a new version which will include a fix.

In the meantime, those notices won't break your website. However, since you're displaying errors, the pages may have problems while loading because as you can see there a warning bellow the notices saying `Cannot modify header information`.

I would recommend to avoid displaying errors and simply logging them in a debug file, using the following configuration in the `wp-config.php` file:

```php
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```

This will make your site behave normally and simply log notices/warning/error in the following file: `/wp-content/debug.log`. If you would like to completely fix the notices, while waiting for the upcoming patch, please follow this instructions:

In the file `wp-content/plugins/acf-extended/includes/core/hooks.php` on `line:286`. Replace those 2 lines:

```php
$field_group = apply_filters("acfe/prepare_field_group/ID={$field_group['ID']}",    $field_group);
$field_group = apply_filters("acfe/prepare_field_group/key={$field_group['key']}",  $field_group);
```

With this code:

```php
if(isset($field_group['ID']))
    $field_group = apply_filters("acfe/prepare_field_group/ID={$field_group['ID']}",    $field_group);

if(isset($field_group['key']))
    $field_group = apply_filters("acfe/prepare_field_group/key={$field_group['key']}",  $field_group);
```

Sorry for the inconvenience.

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up to let you know that the latest ACF Extended 0.8.8.1 patch fixed that issue.

Sorry for the inconvenience.

Have a nice day!

Regards.
