### ISSUE TITLE
Feature request: Conditions value cpt

### ISSUE THREAD

**Issue by wpsumo** [acf-extended/ACF-Extended#76]
**Describe the solution you'd like**
There might be several of fields which is used in ACF field groups but not used on all CPTS. such example can be settings and hero block.

On one cpt it needs some fields while on other not. It would be great to have custom post types in the conditions. So we can exclude and hide specific acf fields if cpt == my custom post type

----
Same with the mutliingual WPML/Polylang if language is. Any update on that one?

@acf-extended FYI.

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! Unfortunately the Field Condition UI is Javascript only and only allow field value condition right now. Adding other value type such as "Post Type" would require a complete rework of the whole feature.

I know that the ACF developer has plans to rework that feature to allow a more flexible & modern API. I'll wait for the feature rework release to see if that can be done. Until then, I would recommend to create different field groups for different locations, since Field Group condition allow you this kind of customization.

Hope it helps!

Regards.

**Comment by wpsumo** [comment]
Yeah they told me something about that as well. Just thought it would be a simple function that was missing but was wrong. Thanks for that and let's wait for the rework of the API. 

Did you add this to the roadmap for the future as it was closed.

**Comment by acf-extended** [comment]
Hello,

There are already multiple features request in the Trello based on this request:
https://trello.com/c/CNO4Umcm/151-conditial-logic-based-on-language
https://trello.com/c/vO1JEk5m/209-fields-conditional-logic-for-taxonomy-terms-values

You can check the Trello board here: https://trello.com/b/QEgpU7CL/acf-extended

I'll wait for the release of the new ACF Conditional Logic before deciding where to start.

Regards.
